import { StyleSheet, Platform } from 'react-native';

const baseStyles = {
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    header: {
        backgroundColor: '#2563eb',
        paddingTop: Platform.OS === 'android' ? 16 : 50,
        paddingBottom: 20,
        paddingHorizontal: 16,
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#fff',
    },
    headerPlaceholder: {
        width: 40,
    },
    addButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    viewToggle: {
        flexDirection: 'row',
        margin: 16,
        marginBottom: 12,
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 4,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    viewButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        borderRadius: 10,
        gap: 6,
    },
    viewButtonActive: {
        backgroundColor: '#eff6ff',
    },
    viewButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
    },
    viewButtonTextActive: {
        color: '#2563eb',
    },
    filtrosContainer: {
        flexDirection: 'row',
        marginHorizontal: 16,
        marginBottom: 16,
        gap: 8,
    },
    filtroChip: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        gap: 6,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    filtroChipText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#1f2937',
        flex: 1,
    },
    filtroChipBadge: {
        backgroundColor: '#eff6ff',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 8,
        minWidth: 20,
        alignItems: 'center',
    },
    filtroChipBadgeText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#2563eb',
    },
    calendarSection: {
        backgroundColor: '#fff',
        marginHorizontal: 16,
        marginBottom: 16,
        borderRadius: 16,
        padding: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    monthSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    monthButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
    },
    monthButtonText: {
        color: '#2563eb',
    },
    monthText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1f2937',
    },
    calendar: {},
    weekDays: {
        flexDirection: 'row',
        marginBottom: 8,
    },
    weekDay: {
        flex: 1,
        alignItems: 'center',
    },
    weekDayText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6b7280',
    },
    daysGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    dayCell: {
        width: '14.28%',
        aspectRatio: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    dayContent: {
        width: '80%',
        height: '80%',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    dayContentSelected: {
        backgroundColor: '#2563eb',
    },
    dayContentToday: {
        borderWidth: 2,
        borderColor: '#2563eb',
    },
    dayText: {
        fontSize: 13,
        fontWeight: '500',
        color: '#1f2937',
    },
    dayTextSelected: {
        color: '#fff',
        fontWeight: '700',
    },
    dayTextToday: {
        color: '#2563eb',
        fontWeight: '700',
    },
    dayIndicators: {
        flexDirection: 'row',
        gap: 2,
        marginTop: 2,
        justifyContent: 'center',
    },
    dayIndicator: {
        width: 5,
        height: 5,
        borderRadius: 2.5,
        backgroundColor: '#3b82f6',
    },
    sectionHeader: {
        paddingHorizontal: 20,
        paddingBottom: 12,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 4,
    },
    sectionCount: {
        fontSize: 13,
        color: '#6b7280',
    },
    incidenciasList: {
        paddingHorizontal: 16,
        gap: 12,
    },
    incidenciaCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    tipoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        gap: 12,
    },
    tipoIcon: {
        width: 40,
        height: 40,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tipoIconSmall: {
        width: 36,
        height: 36,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tipoInfo: {
        flex: 1,
    },
    tipoText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1f2937',
        marginBottom: 2,
    },
    fechaText: {
        fontSize: 12,
        color: '#6b7280',
    },
    estadoBadge: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    motivoText: {
        fontSize: 14,
        color: '#475569',
        lineHeight: 20,
        marginBottom: 8,
    },
    diasBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        backgroundColor: '#f3f4f6',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        gap: 4,
    },
    diasText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6b7280',
    },
    expandedContent: {
        marginTop: 12,
    },
    divider: {
        height: 1,
        backgroundColor: '#e5e7eb',
        marginBottom: 12,
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    detailLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: '#6b7280',
        flex: 1,
    },
    detailValue: {
        fontSize: 13,
        color: '#1f2937',
        flex: 2,
        textAlign: 'right',
    },
    cancelButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 12,
        paddingVertical: 10,
        borderRadius: 10,
        backgroundColor: '#fef2f2',
        gap: 6,
    },
    cancelButtonText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#ef4444',
    },
    emptyContainer: {
        alignItems: 'center',
        paddingVertical: 60,
        paddingHorizontal: 20,
    },
    emptyTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1f2937',
        marginTop: 16,
        marginBottom: 8,
    },
    emptyText: {
        fontSize: 14,
        color: '#6b7280',
        textAlign: 'center',
    },
    modalOverlayBottomSheet: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalBackdrop: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    modalSheetContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingBottom: Platform.OS === 'ios' ? 34 : 20,
        maxHeight: '70%',
    },
    modalSheetHandle: {
        width: 40,
        height: 4,
        backgroundColor: '#d1d5db',
        borderRadius: 2,
        alignSelf: 'center',
        marginTop: 12,
        marginBottom: 8,
    },
    modalListHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    modalListTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
    },
    modalListItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    modalListItemActive: {
        backgroundColor: '#eff6ff',
    },
    modalListItemLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    modalListItemText: {
        fontSize: 15,
        fontWeight: '500',
        color: '#1f2937',
    },
    modalListItemTextActive: {
        color: '#2563eb',
        fontWeight: '600',
    },
    modalListItemBadge: {
        backgroundColor: '#f3f4f6',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        minWidth: 28,
        alignItems: 'center',
    },
    modalListItemBadgeText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#6b7280',
    },
    modalOverlayCreate: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalBackdropCreate: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    modalCreateContainer: {
        height: '75%',
    },
    modalCreateContent: {
        flex: 1,
        backgroundColor: '#f8fafc',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 20,
        paddingBottom: 20,
        paddingHorizontal: 20,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#1f2937',
    },
    closeButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#f3f4f6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalBody: {
        flex: 1,
        padding: 20,
        backgroundColor: '#f8fafc',
    },
    sectionContainer: {
        marginBottom: 24,
    },
    sectionLabel: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 12,
    },
    selectInput: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 14,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    selectInputContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        flex: 1,
    },
    selectInputText: {
        fontSize: 14,
        color: '#1f2937',
        fontWeight: '500',
    },
    selectInputPlaceholder: {
        fontSize: 14,
        color: '#9ca3af',
    },
    dateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 12,
    },
    dateCompact: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 12,
        gap: 10,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    dateCompactActive: {
        borderColor: '#3b82f6',
        borderWidth: 2,
    },
    dateCompactInfo: {
        flex: 1,
    },
    dateCompactLabel: {
        fontSize: 11,
        fontWeight: '600',
        color: '#6b7280',
        marginBottom: 2,
    },
    dateCompactValue: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1f2937',
    },
    dateArrow: {
        paddingHorizontal: 2,
    },
    datePickerInline: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 8,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        alignItems: 'center',
    },
    durationSummary: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f9ff',
        padding: 10,
        borderRadius: 10,
        gap: 8,
    },
    durationText: {
        fontSize: 13,
        color: '#475569',
        fontWeight: '500',
    },
    durationValue: {
        fontSize: 14,
        fontWeight: '700',
        color: '#8b5cf6',
    },
    motivoCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        overflow: 'hidden',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    motivoHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 14,
        backgroundColor: '#f9fafb',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        gap: 8,
    },
    motivoPlaceholder: {
        fontSize: 13,
        color: '#6b7280',
        fontWeight: '500',
    },
    motivoInput: {
        padding: 16,
        fontSize: 15,
        color: '#1f2937',
        minHeight: 140,
        maxHeight: 200,
        lineHeight: 22,
    },
    modalFooter: {
        flexDirection: 'row',
        gap: 12,
        padding: 20,
        paddingBottom: Platform.OS === 'ios' ? 34 : 20,
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        backgroundColor: '#fff',
    },
    cancelButtonModal: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        backgroundColor: '#f3f4f6',
        alignItems: 'center',
    },
    cancelButtonModalText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#6b7280',
    },
    createButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        backgroundColor: '#3b82f6',
        alignItems: 'center',
    },
    createButtonDisabled: {
        opacity: 0.5,
    },
    createButtonText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#fff',
    },
};

export const incidenciasStyles = StyleSheet.create(baseStyles);

export const incidenciasStylesDark = StyleSheet.create({
    ...baseStyles,
    container: {
        ...baseStyles.container,
        backgroundColor: '#0f172a',
    },
    header: {
        ...baseStyles.header,
        backgroundColor: '#1e40af',
    },
    viewToggle: {
        ...baseStyles.viewToggle,
        backgroundColor: '#1e293b',
    },
    viewButtonActive: {
        ...baseStyles.viewButtonActive,
        backgroundColor: '#334155',
    },
    filtroChip: {
        ...baseStyles.filtroChip,
        backgroundColor: '#1e293b',
    },
    filtroChipText: {
        ...baseStyles.filtroChipText,
        color: '#f1f5f9',
    },
    filtroChipBadge: {
        ...baseStyles.filtroChipBadge,
        backgroundColor: '#334155',
    },
    calendarSection: {
        ...baseStyles.calendarSection,
        backgroundColor: '#1e293b',
    },
    monthButtonText: {
        ...baseStyles.monthButtonText,
        color: '#60a5fa',
    },
    monthText: {
        ...baseStyles.monthText,
        color: '#f1f5f9',
    },
    weekDayText: {
        ...baseStyles.weekDayText,
        color: '#94a3b8',
    },
    dayText: {
        ...baseStyles.dayText,
        color: '#e2e8f0',
    },
    dayTextToday: {
        ...baseStyles.dayTextToday,
        color: '#60a5fa',
    },
    sectionTitle: {
        ...baseStyles.sectionTitle,
        color: '#f1f5f9',
    },
    incidenciaCard: {
        ...baseStyles.incidenciaCard,
        backgroundColor: '#1e293b',
    },
    tipoText: {
        ...baseStyles.tipoText,
        color: '#f1f5f9',
    },
    motivoText: {
        ...baseStyles.motivoText,
        color: '#cbd5e1',
    },
    diasBadge: {
        ...baseStyles.diasBadge,
        backgroundColor: '#334155',
    },
    divider: {
        ...baseStyles.divider,
        backgroundColor: '#334155',
    },
    detailValue: {
        ...baseStyles.detailValue,
        color: '#e2e8f0',
    },
    cancelButton: {
        ...baseStyles.cancelButton,
        backgroundColor: '#4c1d1d',
    },
    emptyTitle: {
        ...baseStyles.emptyTitle,
        color: '#f1f5f9',
    },
    modalSheetContent: {
        ...baseStyles.modalSheetContent,
        backgroundColor: '#1e293b',
    },
    modalSheetHandle: {
        ...baseStyles.modalSheetHandle,
        backgroundColor: '#475569',
    },
    modalListHeader: {
        ...baseStyles.modalListHeader,
        borderBottomColor: '#334155',
    },
    modalListTitle: {
        ...baseStyles.modalListTitle,
        color: '#f1f5f9',
    },
    modalListItem: {
        ...baseStyles.modalListItem,
        borderBottomColor: '#334155',
    },
    modalListItemActive: {
        ...baseStyles.modalListItemActive,
        backgroundColor: '#334155',
    },
    modalListItemText: {
        ...baseStyles.modalListItemText,
        color: '#f1f5f9',
    },
    modalListItemBadge: {
        ...baseStyles.modalListItemBadge,
        backgroundColor: '#475569',
    },
    modalListItemBadgeText: {
        ...baseStyles.modalListItemBadgeText,
        color: '#e2e8f0',
    },
    modalCreateContent: {
        ...baseStyles.modalCreateContent,
        backgroundColor: '#0f172a',
    },
    modalHeader: {
        ...baseStyles.modalHeader,
        backgroundColor: '#1e293b',
        borderBottomColor: '#334155',
    },
    modalTitle: {
        ...baseStyles.modalTitle,
        color: '#f1f5f9',
    },
    closeButton: {
        ...baseStyles.closeButton,
        backgroundColor: '#334155',
    },
    modalBody: {
        ...baseStyles.modalBody,
        backgroundColor: '#0f172a',
    },
    sectionLabel: {
        ...baseStyles.sectionLabel,
        color: '#f1f5f9',
    },
    selectInput: {
        ...baseStyles.selectInput,
        backgroundColor: '#1e293b',
        borderColor: '#334155',
    },
    selectInputText: {
        ...baseStyles.selectInputText,
        color: '#f1f5f9',
    },
    dateCompact: {
        ...baseStyles.dateCompact,
        backgroundColor: '#1e293b',
        borderColor: '#334155',
    },
    dateCompactActive: {
        ...baseStyles.dateCompactActive,
        borderColor: '#3b82f6',
    },
    dateCompactLabel: {
        ...baseStyles.dateCompactLabel,
        color: '#94a3b8',
    },
    dateCompactValue: {
        ...baseStyles.dateCompactValue,
        color: '#f1f5f9',
    },
    datePickerInline: {
        ...baseStyles.datePickerInline,
        backgroundColor: '#1e293b',
        borderColor: '#334155',
    },
    durationSummary: {
        ...baseStyles.durationSummary,
        backgroundColor: '#1e3a5f',
    },
    durationText: {
        ...baseStyles.durationText,
        color: '#cbd5e1',
    },
    durationValue: {
        ...baseStyles.durationValue,
        color: '#a78bfa',
    },
    motivoCard: {
        ...baseStyles.motivoCard,
        backgroundColor: '#1e293b',
        borderColor: '#334155',
    },
    motivoHeader: {
        ...baseStyles.motivoHeader,
        backgroundColor: '#0f172a',
        borderBottomColor: '#334155',
    },
    motivoPlaceholder: {
        ...baseStyles.motivoPlaceholder,
        color: '#94a3b8',
    },
    motivoInput: {
        ...baseStyles.motivoInput,
        color: '#f1f5f9',
    },
    modalFooter: {
        ...baseStyles.modalFooter,
        borderTopColor: '#334155',
        backgroundColor: '#1e293b',
    },
    cancelButtonModal: {
        ...baseStyles.cancelButtonModal,
        backgroundColor: '#334155',
    },
});
